# Copyright (c) .NET Foundation and Contributors
# See LICENSE file in the project root for full license information.

steps:
  - task: PowerShell@2
    displayName: Check nf-interpreter to test
    condition: ne(variables['System.PullRequest.PullRequestNumber'], '')
    inputs:
      failOnStderr: false
      targetType: "inline"
      script: |

        # prepare GitHub API headers using token auth
        $headers = @{
          Authorization = "token $env:GITHUB_TOKEN"
          'User-Agent'  = 'azure-pipelines'
          Accept        = 'application/vnd.github+json'
        }

        # find PR
        "Getting PR #$env:System_PullRequest_PullRequestNumber details..." | Write-Host -ForegroundColor White -NoNewline
        $pr = Invoke-RestMethod `
          -Uri "https://api.github.com/repos/$env:Build_Repository_Name/pulls/$env:System_PullRequest_PullRequestNumber" `
          -Headers $headers `
          -Method GET

        if($($pr.number) -eq "$env:System_PullRequest_PullRequestNumber")
        {
          'OK' | Write-Host -ForegroundColor Green
        }

        # grab PR commit message
        $prCommitMessage = $($pr.body)

        # look for test prompt in PR commit message
        # pattern is "[tested against nanoclr buildId NNN]"

        if($prCommitMessage -match "\[tested against nanoclr buildId (\d+)\]")
        {
          $buildId = $matches[1]
          "AZDO build ID found: $buildId" | Write-Host -ForegroundColor White

          echo "##vso[task.setvariable variable=NFINTERPRETER_BUILDID]$buildId"
        }
        else
        {
          "No build ID found" | Write-Host -ForegroundColor Red
        }
    env:
      GITHUB_TOKEN: $(GitHubToken)

  - task: DownloadPipelineArtifact@2
    condition: ne(variables['NFINTERPRETER_BUILDID'], '')
    displayName: Download nanoCLR preview
    inputs:
      buildType: specific
      project: 'nf-interpreter'
      definition: '34'
      buildVersionToDownload: specific
      allowFailedBuilds: true
      buildId: $(NFINTERPRETER_BUILDID)
      artifactName: 'nanoclr_dll'
      targetPath: '$(Agent.TempDirectory)/nanoclr'

  - task: PowerShell@2
    condition: ne(variables['NFINTERPRETER_BUILDID'], '')
    displayName: Flag availability of local nanoCLR
    name: NANOCLR_CHECK
    inputs:
      targetType: 'inline'
      script: |
        Write-Host "##vso[task.setvariable variable=HAS_LOCAL_NANOCLR;isOutput=true]true"
