// Licensed to the .NET Foundation under one or more agreements.
// The .NET Foundation licenses this file to you under the MIT license.

namespace System.Runtime.CompilerServices
{
    /// <summary>
    /// Distinguishes a compiler-generated element from a user-generated element. This class cannot be inherited.
    /// </summary>
    /// <remarks>
    /// <para>
    /// Apply the <see cref="CompilerGeneratedAttribute"/> attribute to any application element to indicate that the element is generated by a compiler.
    /// </para>
    /// <para>
    /// Use the <see cref="CompilerGeneratedAttribute"/> attribute to determine whether an element is added by a compiler or authored directly in source code.
    /// </para>
    /// </remarks>
    [AttributeUsage(AttributeTargets.All, Inherited = true)]
    public sealed class CompilerGeneratedAttribute : Attribute
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="CompilerGeneratedAttribute"/> class.
        /// </summary>
        public CompilerGeneratedAttribute() { }
    }
}
