// Licensed to the .NET Foundation under one or more agreements.
// The .NET Foundation licenses this file to you under the MIT license.

namespace System.Runtime.CompilerServices
{
    /// <summary>
    /// When a class, enum, or struct is marked with <see cref="ExcludeTypeAttribute"/> it will be excluded from the PE files and stubbs generated by .NET nanoFramework metadata processor.
    /// </summary>
    /// <remarks>
    /// <para>
    /// This attribute is exclusive to .NET nanoFramework and is not part of the .NET Standard.
    /// </para>
    /// <para>
    /// [!Important] Placing this attribute on a class will cause the type from being excluded from the assembly metadata and therefore it will not be available at all in assemblies using or referencing them.
    /// </para>
    /// </remarks>
    [AttributeUsage(AttributeTargets.Class | AttributeTargets.Enum | AttributeTargets.Struct, AllowMultiple = false, Inherited = true)]
    public class ExcludeTypeAttribute : Attribute
    {
    }
}
